table 'Project Assignment Schedule'
	lineageTag: 4eba6245-3a85-4ad3-9c76-95e59b91b329

	column Id
		dataType: string
		lineageTag: cf69cb93-fcca-4ffb-bb19-42ed67c5008d
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Krow__Project_Assignment__c
		dataType: string
		lineageTag: 6c9d442c-28ab-4fb2-8a9c-71f48d4af16d
		summarizeBy: none
		sourceColumn: Krow__Project_Assignment__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Krow__End_Date__c
		dataType: dateTime
		formatString: d-m-yyyy
		lineageTag: 3d40b2b9-d093-4d83-9359-662b1d3efc8d
		summarizeBy: none
		sourceColumn: Krow__End_Date__c

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation Format = <Format Format="DateTimeCustom"><DateTimes><DateTime LCID="1043" Group="ShortDate" FormatString="d-M-yyyy" /></DateTimes></Format>

	column Krow__Fri_Task__c
		dataType: double
		lineageTag: a8f4b7f6-ab9e-477e-8405-cae071db034c
		summarizeBy: sum
		sourceColumn: Krow__Fri_Task__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Fri__c
		dataType: double
		lineageTag: 500f5471-6afe-426a-8236-4f4fcac924bc
		summarizeBy: sum
		sourceColumn: Krow__Fri__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Mon_Task__c
		dataType: double
		lineageTag: d6a3c040-fede-46c3-9ca1-92e2fab265c2
		summarizeBy: sum
		sourceColumn: Krow__Mon_Task__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Mon__c
		dataType: double
		lineageTag: 845a758d-2bf5-4269-b053-16602467ef8f
		summarizeBy: sum
		sourceColumn: Krow__Mon__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Sat_Task__c
		dataType: double
		lineageTag: dd1904f2-6684-4e20-b350-9e1757c7119b
		summarizeBy: sum
		sourceColumn: Krow__Sat_Task__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Sat__c
		dataType: double
		lineageTag: a3f93b2f-b883-43a8-9ea5-5c4e83c76cae
		summarizeBy: sum
		sourceColumn: Krow__Sat__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Start_Date__c
		dataType: dateTime
		formatString: d-m-yyyy
		lineageTag: a7b4e0ab-98cb-40c3-93ec-9e13d8e5443b
		summarizeBy: none
		sourceColumn: Krow__Start_Date__c

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation Format = <Format Format="DateTimeCustom"><DateTimes><DateTime LCID="1043" Group="ShortDate" FormatString="d-M-yyyy" /></DateTimes></Format>

	column Krow__Status__c
		dataType: string
		lineageTag: f0d435fb-ddfe-4b90-8ab5-ec1b4008c4ff
		summarizeBy: none
		sourceColumn: Krow__Status__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Krow__Sun_Task__c
		dataType: double
		lineageTag: 2555b16d-e459-4f34-be89-e3e6d86326eb
		summarizeBy: sum
		sourceColumn: Krow__Sun_Task__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Sun__c
		dataType: double
		lineageTag: 936c917a-50d3-4270-b360-07350de9f0e6
		summarizeBy: sum
		sourceColumn: Krow__Sun__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Thu_Task__c
		dataType: double
		lineageTag: c1194131-2277-4810-89e8-f2532ce84191
		summarizeBy: sum
		sourceColumn: Krow__Thu_Task__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Thu__c
		dataType: double
		lineageTag: c6d2a045-b0d7-4fa7-8120-565a12353204
		summarizeBy: sum
		sourceColumn: Krow__Thu__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Total_Week_Project_Schedule_Hours__c
		dataType: double
		lineageTag: 529c0e0b-386b-463a-bea9-98b81804d0cb
		summarizeBy: sum
		sourceColumn: Krow__Total_Week_Project_Schedule_Hours__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Tue_Task__c
		dataType: double
		lineageTag: 402643c0-d39d-4d95-a20a-550c45897395
		summarizeBy: sum
		sourceColumn: Krow__Tue_Task__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Tue__c
		dataType: double
		lineageTag: 75b5518b-fc79-4df1-94cf-971285dbe5d7
		summarizeBy: sum
		sourceColumn: Krow__Tue__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Wed_Task__c
		dataType: double
		lineageTag: 21957dea-94ec-430e-8b51-d5c5dc5b6378
		summarizeBy: sum
		sourceColumn: Krow__Wed_Task__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Wed__c
		dataType: double
		lineageTag: ef462602-b71f-42c9-8f5b-d6ad28651af5
		summarizeBy: sum
		sourceColumn: Krow__Wed__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

	column Krow__Note__c
		dataType: string
		lineageTag: 4fb33eb9-ff9a-4041-ac4a-28020390ab85
		summarizeBy: none
		sourceColumn: Krow__Note__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Assigned_User__c
		dataType: string
		lineageTag: 1b09b361-bfed-4318-b6b7-d21979caca1d
		summarizeBy: none
		sourceColumn: Assigned_User__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Sprint__c
		dataType: string
		lineageTag: b2ea017d-372e-427f-8bed-58ca70c509ac
		summarizeBy: none
		sourceColumn: Sprint__c

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	partition 'Project Assignment Schedule-3e94e39a-0f19-4549-8156-30ae6c72da37' = m
		mode: import
		source =
				let
				    Bron = Salesforce.Data("https://growteq.my.salesforce.com", [ApiVersion=48]),
				    Krow__Project_Assignment_Schedule__c = Bron{[Name="Krow__Project_Assignment_Schedule__c"]}[Data],
				    #"Andere kolommen verwijderd" = Table.SelectColumns(Krow__Project_Assignment_Schedule__c,{"Id", "Krow__Project_Assignment__c", "Krow__End_Date__c", "Krow__Fri_Task__c", "Krow__Fri__c", "Krow__Mon_Task__c", "Krow__Mon__c", "Krow__Sat_Task__c", "Krow__Sat__c", "Krow__Start_Date__c", "Krow__Status__c", "Krow__Sun_Task__c", "Krow__Sun__c", "Krow__Thu_Task__c", "Krow__Thu__c", "Krow__Total_Week_Project_Schedule_Hours__c", "Krow__Tue_Task__c", "Krow__Tue__c", "Krow__Wed_Task__c", "Krow__Wed__c", "Krow__Note__c", "Assigned_User__c", "Sprint__c"})
				in
				    #"Andere kolommen verwijderd"

	annotation PBI_ResultType = Table

