table FeitSprintCapaciteit
	lineageTag: 31a5dc02-49e1-4f15-b065-05613bab5222

	column MedewerkerKey
		dataType: int64
		formatString: 0
		lineageTag: e6cc7c18-ce21-4725-97e3-2c2ea9a66810
		summarizeBy: none
		sourceColumn: MedewerkerKey

		annotation SummarizationSetBy = Automatic

	column WeekNummer
		dataType: int64
		formatString: 0
		lineageTag: 56b196b7-a53b-49cb-8011-3cfbf31984a5
		summarizeBy: none
		sourceColumn: WeekNummer

		annotation SummarizationSetBy = User

	column Team
		dataType: string
		lineageTag: f74db200-b94c-4521-baf6-33c06d4985e9
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column TeamNaam
		dataType: string
		lineageTag: c2d19015-52bb-4f3f-998c-7960d9b05411
		summarizeBy: none
		sourceColumn: TeamNaam

		annotation SummarizationSetBy = Automatic

	column SprintNummer
		dataType: string
		lineageTag: fe70de1c-b402-4797-81d9-eb8a84135bce
		summarizeBy: none
		sourceColumn: SprintNummer

		annotation SummarizationSetBy = Automatic

	column SprintNaam
		dataType: string
		lineageTag: e8e14653-6966-4322-9a35-dd8abed05e1f
		summarizeBy: none
		sourceColumn: SprintNaam

		annotation SummarizationSetBy = Automatic

	column TotaalUren
		dataType: double
		lineageTag: 1da6b4e6-bd7c-43db-9417-e0ae13725399
		summarizeBy: none
		sourceColumn: TotaalUren

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column JaarWeek
		dataType: string
		lineageTag: 86c2c9cc-14e1-476f-8d55-af96223d443b
		summarizeBy: none
		sourceColumn: JaarWeek

		annotation SummarizationSetBy = Automatic

	column Datum
		dataType: dateTime
		formatString: General Date
		lineageTag: d854d359-fc03-438d-9483-3decf35ec376
		summarizeBy: none
		sourceColumn: Datum

		variation Variation
			isDefault
			relationship: 476b7836-aa0d-4825-831d-67cc2266df31
			defaultHierarchy: LocalDateTable_5928f65d-9ca1-4ac2-9165-72b19979420a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition FeitSprintCapaciteit = m
		mode: import
		source =
				let
				    Source = Sql.Databases("6axb2xb7kkaujnz5lqc35xokhe-jtbihupxli3unlh5ujz4xsn2je.datawarehouse.fabric.microsoft.com"),
				    #"Operationeel Dashboard" = Source{[Name="Operationeel Dashboard"]}[Data],
				    s4_inf_SprintCapaciteit = #"Operationeel Dashboard"{[Schema="s4_inf",Item="SprintCapaciteit"]}[Data],
				
				    // Toevoegen van Jaar-Week kolom
				    #"Toegevoegde JaarWeek" = Table.AddColumn(s4_inf_SprintCapaciteit, "JaarWeek", each
				        let
				            datum = [Datum],
				            jaar = Date.Year(datum),
				            week = Date.WeekOfYear(datum)
				        in
				            Text.From(jaar)  & Text.PadStart(Text.From(week), 2, "0"),
				        type text
				    )
				in
				    #"Toegevoegde JaarWeek"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

