table '1. Meetwaarden'
	lineageTag: a6b5c615-6f4e-4472-aa84-1a87cc8d7337

	measure 'Aantal Actieve Medewerkers' = ```
			
			CALCULATE(
			    COUNT(DimMedewerkers[Medewerker]),
			    NOT(ISBLANK(DimMedewerkers[DatumIndienst])),
			    ISBLANK(DimMedewerkers[DatumUitdienst])
			)
			
			```
		lineageTag: 51a977cd-58d4-4811-b482-10c673c3b9c9

	measure 'Aantal FTE' = ```
			
			SUM(FeitFormatieBezetting[FTE])
			
			```
		lineageTag: c7750c36-7f8a-4abb-bbea-6a0aaf919303

	measure 'Aantal Medewerkers' = COUNT(DimMedewerkers[Medewerker])
		lineageTag: 63de61fb-3998-424d-af1d-160c250a40c4

	measure 'Aantal Medewerkers In Dienst' = ```
			
			CALCULATE(
			    COUNT(DimMedewerkers[MedewerkerId]),
			    USERELATIONSHIP(DimDatum[Datum], DimMedewerkers[DatumInDienst])
			)
			
			```
		lineageTag: a09e1671-7d8e-4e87-8af5-e931a298c77c

	measure 'Aantal Medewerkers In Dienst Vorig Jaar' = ```
			
			CALCULATE(
			    COUNT(DimMedewerkers[MedewerkerId]),
			    USERELATIONSHIP(DimDatum[Datum], DimMedewerkers[DatumInDienst]),
			    YEAR(DimDatum[Datum]) = YEAR(TODAY()) - 1
			)
			
			```
		lineageTag: 82ad75bb-6f62-4023-b22c-0bb35ed7c967

	measure 'Aantal Medewerkers Uit Dienst Dit Jaar' = ```
			
			CALCULATE(
			    COUNT(DimMedewerkers[MedewerkerId]),
			    USERELATIONSHIP(DimDatum[Datum], DimMedewerkers[DatumUitDienst])
			)
			
			```
		lineageTag: c0310e19-fdb6-4736-be17-86c4609bcf65

	measure 'Aantal Medewerkers Uit Dienst Vorig Jaar' = ```
			
			CALCULATE(
			    COUNT(DimMedewerkers[MedewerkerId]),
			    USERELATIONSHIP(DimDatum[Datum], DimMedewerkers[DatumUitDienst]),
			    YEAR(DimDatum[Datum]) = YEAR(TODAY()) - 1
			)
			
			```
		lineageTag: 7d37a5c6-d070-4c47-9e11-558a48d7ca3a

	measure 'Aantal Projecten met Taakregels' = ```
			
			CALCULATE(
			    [Aantal Actieve Projecten], -- Gebruik de bestaande measure
			    USERELATIONSHIP(DimTaakregels[ProjectKey], DimProjecten[ProjectKey]) -- Specificeer de alternatieve relatie
			)
			
			```
		lineageTag: da66381b-6cb1-4cd2-8201-9bf7d1fae538

	measure 'Aantal skills' = COUNT(FeitMedewerkerSkills[MedewerkerSkillKey])
		lineageTag: f1b1db5b-06d9-4154-9519-b701a9b4a092

	measure 'Aantal Taakregels met Project' = ```
			
			CALCULATE(
			    COUNTROWS(DimTaakregels), -- Telt het aantal taakregels
			    USERELATIONSHIP(DimTaakregels[ProjectKey], DimProjecten[ProjectKey]) -- Specificeert de alternatieve relatie
			)
			
			```
		lineageTag: 17666a51-64e9-4463-a5e2-fa3df580423a

	measure 'Aantal Verlof Dagen Komende 12 Maanden' = ```
			
			CALCULATE(
			    DISTINCTCOUNT(FeitVerlofAanvragen[FeitVerlofaanvraagKey])
			    )
			
			
			```
		lineageTag: 5851aa51-84cd-47bc-9fbd-6656a2471974

	measure AantalBeschikbareUren = SUM(FeitRoosterUren[Aantal_uren_per_week])
		lineageTag: c571833c-2a1f-490b-b17f-ea8f94cf6024

	measure AantalBeschikbareUrenGeselecteerdePeriode = ```
			
			VAR MinDatum = MIN(DimDatum[Datum])  -- Begin van de geselecteerde periode
			VAR MaxDatum = MAX(DimDatum[Datum])  -- Einde van de geselecteerde periode
			VAR AantalUniekeWeken = DISTINCTCOUNT(DimDatum[WeekNummer])  -- Aantal unieke geselecteerde weken
			
			RETURN 
			SUM(FeitRoosterUren[Aantal_uren_per_week]) * AantalUniekeWeken
			
			```
		lineageTag: e882428b-d5bb-472f-a33d-7e5a8c9c2ee6

	measure 'Bezettingsgraad YTD' = ```
			
			DIVIDE(
			    CALCULATE(
			        [Geschreven ProjectUren Laatste 12 maanden], 
			        FILTER(
			            ALL(DimDatum), 
			            DimDatum[Datum] >= DATE(YEAR(TODAY()), 1, 1) &&  -- Begin van huidig jaar
			            DimDatum[Datum] <= TODAY()  -- Tot en met vandaag
			        )
			    ),
			    CALCULATE(
			        [Aantal Geschreven Uren], 
			        FILTER(
			            ALL(DimDatum), 
			            DimDatum[Datum] >= DATE(YEAR(TODAY()), 1, 1) &&  -- Begin van huidig jaar
			            DimDatum[Datum] <= TODAY()  -- Tot en met vandaag
			        )
			    ),
			    BLANK()  -- Voorkomt deling door nul
			)
			
			```
		lineageTag: daeaef2c-c080-40d8-bdab-de176b661bf8

	measure BezettingsgraadBeschikbareUren = ```
			[AantalBeschikbareUrenGeselecteerdePeriode] - [Aantal Geplande Verlofuren] 
			```
		lineageTag: d035d5d6-5ad3-4e8d-bcd0-78cc4d38c0ff

	measure vHJ = if(ISFILTERED(DimDatumFilter[Jaar]), max(DimDatumFilter[Jaar]), YEAR(TODAY()))
		displayFolder: Calculatiegroepen
		lineageTag: f150e38f-9c9a-42c4-a259-1ddcf2a85f19

	measure vHM = if(ISFILTERED(DimDatumFilter[MaandNaam]), max(DimDatumFilter[MaandNummer]), MONTH(TODAY()))
		displayFolder: Calculatiegroepen
		lineageTag: 3c5b8f96-ee05-41d1-b8a2-50a56067e209

	measure vHMnrRel =
			
			VAR Jr = [vHJ]
			VAR Mnd = [vHM]
			RETURN
			CALCULATE(
			    max(DimDatumFilter[MaandNrRelatief])
			    , FILTER(ALL(DimDatumFilter), DimDatumFilter[Jaar] = Jr && DimDatumFilter[MaandNummer] = Mnd))
		displayFolder: Calculatiegroepen
		lineageTag: 1a413d78-2f0e-496d-aeab-cfa957d4e7ea

	measure Brutomarge = [Omzet ex. BTW] - [Factuurkosten]
		displayFolder: Commercieel
		lineageTag: 21584dc8-cb76-46fc-b838-48c8e476a1f1

	measure 'Brutomarge %' = [Brutomarge] / [Omzet ex. BTW]
		displayFolder: Commercieel
		lineageTag: c18ff68d-542b-478c-bbed-eda1260cfd46

	measure 'Commerciële waarden uren' = ```
			
			SUMX(
			    FeitGeschrevenUren, 
			    [Aantal geschreven Uren] * RELATED(DimMedewerkers[Uurtarief])
			)
			
			```
		displayFolder: Commercieel
		lineageTag: 57f8766e-0956-4c6a-8b2f-2e36287b30af

	measure 'Measure 2'
		isHidden
		displayFolder: Commercieel
		lineageTag: 34609d2e-ba40-473b-bf0b-79670bf5395c

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Declarabiliteit = [Facturabele Uren] / [Aantal geschreven Uren]
		displayFolder: Commercieel
		lineageTag: f1b9fe61-2ccb-4395-8bf8-1f4c49fcb716

	measure ExterneMedewerkerOmzet = ```
			
			CALCULATE(
			    [Omzet ex. BTW], -- Som van de uren
			    FILTER(
			        DimMedewerkers, 
			        DimMedewerkers[IsExterneMedewerker] = 1 -- Filter alleen externe medewerkers
			    )
			)
			
			```
		displayFolder: Commercieel
		lineageTag: c96c56b1-e87a-4bda-b77d-c54489796fe0

	measure 'ExterneMedewerkerOmzet Vorig Jaar' = ```
			
			CALCULATE(
			    [Omzet ex. BTW Vorig Jaar], -- Som van de uren
			    FILTER(
			        DimMedewerkers, 
			        DimMedewerkers[IsExterneMedewerker] = 1 -- Filter alleen externe medewerkers
			    )
			)
			
			```
		displayFolder: Commercieel
		lineageTag: ec7b472e-38d8-4915-938d-5b70cc8a44c0

	measure Factuurkosten = SUM(FeitFactuurregels[KostenBedrag])
		displayFolder: Commercieel
		lineageTag: 1a7c13d8-114a-4e80-8e8a-25f6b562f404

	measure 'Gemiddeld Uurtarief' = ```
			
			AVERAGE(FeitFactuurregels[UurTarief])
			
			```
		displayFolder: Commercieel
		lineageTag: 409a93e0-1c3d-40d9-81cf-38b01a7de773

	measure 'Gerealiseerde ProjectOmzet' = SUM(DimProjecten[FacturabeleOmzet])
		displayFolder: Commercieel
		lineageTag: d7565ff5-2c22-4898-9224-4bd59b2b3f16

	measure 'Kosten Vorig Jaar' = ```
			
			CALCULATE(
			    SUM(FeitFactuurregels[KostenBedrag]),
			    SAMEPERIODLASTYEAR(DimDatum[Datum])
			)
			
			```
		displayFolder: Commercieel
		lineageTag: 5e435777-75b0-4673-857b-a760359da8df

	measure KostenExtern = ```
			
			CALCULATE(
			    [Factuurkosten], -- Som van de uren
			    FILTER(
			        DimMedewerkers, 
			        DimMedewerkers[IsExterneMedewerker] = 1 -- Filter alleen externe medewerkers
			    )
			)
			
			```
		displayFolder: Commercieel
		lineageTag: fda04fb2-4baf-4bbc-a1c4-ed43b48f4881

	measure KostenIntern = ```
			
			CALCULATE(
			    [Factuurkosten], -- Som van de uren
			    FILTER(
			        DimMedewerkers, 
			        DimMedewerkers[IsExterneMedewerker] = 0 -- Filter alleen externe medewerkers
			    )
			)
			
			```
		displayFolder: Commercieel
		lineageTag: 30cb1891-3030-4b72-9872-345889e7f111

	measure MedewerkerOmzet = ```
			
			CALCULATE(
			    [Omzet ex. BTW], -- Som van de uren
			    FILTER(
			        DimMedewerkers, 
			        DimMedewerkers[IsExterneMedewerker] = 0 -- Filter alleen externe medewerkers
			    )
			)
			
			```
		displayFolder: Commercieel
		lineageTag: d430e69f-e661-44e1-9836-9d6767714694

	measure 'Omzet ex. BTW' = SUM(FeitFactuurregels[BedragExclBTW])
		displayFolder: Commercieel
		lineageTag: 1df4c79b-8ed8-4378-a5c8-d4b8b42d7b50

	measure 'Omzet ex. BTW Vorig Jaar' = ```
			
			CALCULATE(
			    SUM(FeitFactuurregels[BedragExclBTW]),
			    SAMEPERIODLASTYEAR(DimDatum[Datum])
			)
			
			```
		displayFolder: Commercieel
		lineageTag: 5e940a6e-d963-47ab-b651-5d62fab7f1a5

	measure 'Percentage interne/externe kosten' = [KostenExtern] / [Factuurkosten]
		displayFolder: Commercieel
		lineageTag: 1aea3cad-b6f5-41dd-933d-056dd7ba740d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Percentage interne/externe omzet' = [ExterneMedewerkerOmzet] / [Omzet ex. BTW]
		displayFolder: Commercieel
		lineageTag: 7eda2bfc-4e3b-4756-b761-45a169754832

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Verwachte Omzet' = SUM(DimProjecten[VerwachteOmzet])
		displayFolder: Commercieel
		lineageTag: b4cb7885-1408-4f73-9e36-6c8ced9c7394

	measure 'Geschatte Uren Komende 12 maanden' = ```
			
			CALCULATE(
			    [Geschatte Uren],
			    FILTER(
			        ALL(TimeIntelligence),
			        TimeIntelligence[Calculatie] = "Komende 12 maanden"
			    ),
			    USERELATIONSHIP(DimProjecten[Startdatum], DimDatum[Datum]) -- Activeer de inactieve relatie
			)
			
			```
		lineageTag: d310de9a-9bac-4204-b92f-5d5211f72a1a

	measure 'Nieuwe Medewerkers' =
			CALCULATE(
			    COUNT(DimMedewerkers[MedewerkerId]),
			    FILTER(DimMedewerkers, ISBLANK(DimMedewerkers[DatumUitdienst])))
		formatString: 0
		lineageTag: f2ba8a72-4717-424b-b6c1-084e9fb75d2c

	measure 'Aantal Actieve Projecten' = ```
			
			CALCULATE(
			    [Aantal Projecten],
			    DimProjecten[Projectstatus] = "In Progress",
			    USERELATIONSHIP(DimProjecten[Startdatum], DimDatum[Datum]),
			    USERELATIONSHIP(DimProjecten[PracticeKey], DimPractice[PracticeKey])
			)
			
			```
		displayFolder: Operationeel
		lineageTag: 335176d4-7967-4bb7-961e-dcb0c0e3bf3c

	measure 'Aantal Projecten' = COUNT(DimProjecten[ProjectId])
		displayFolder: Operationeel
		lineageTag: a1223002-0ae3-4647-a539-308dd29bec99

	measure 'Aantal Projecten met uren' =
			
			DISTINCTCOUNT(FeitGeschrevenUren[ProjectKey])
		displayFolder: Operationeel
		lineageTag: cdd2794c-e457-462c-9e44-c8b3308e4550

	measure 'Aantal toekomstige Projecten' = ```
			
			CALCULATE(
			    [Aantal Projecten],
			    DimProjecten[Projectstatus] = "Not Started",
			    USERELATIONSHIP(DimProjecten[Startdatum], DimDatum[Datum]),
			    USERELATIONSHIP(DimProjecten[PracticeKey], DimPractice[PracticeKey])
			)
			
			```
		displayFolder: Operationeel
		lineageTag: e50a8d20-3b09-4ef7-ae1b-04471bdc43b3

	measure 'Afgeronde Projecten' = ```
			
			CALCULATE(
			    DISTINCTCOUNT(DimProjecten[ProjectId]),
			    DimProjecten[Projectstatus] = "Complete",
			    USERELATIONSHIP(DimProjecten[DatumAfgerond], DimDatum[Datum])
			)
			
			```
		displayFolder: Operationeel
		lineageTag: e5fdc980-60a1-436c-907a-1d156e2f0e6e

	measure Bezettingsgraad = [Geschreven ProjectUren Laatste 12 maanden] / [Aantal geschreven Uren]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Operationeel
		lineageTag: be7e396e-76f8-42dd-a39d-ce48a2356981

	measure 'Bezettingsgraad Laatste 12 maanden' =
			
			CALCULATE([Bezettingsgraad],
			FILTER(ALL(TimeIntelligence),
			TimeIntelligence[Calculatie] = "Laatste 12 maanden"))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Operationeel
		lineageTag: 1153ca93-d343-46c7-b43d-8c0a9187cc37

	measure Test_AantalRijen = ```
			
			COUNTROWS(
			    FILTER(
			        ALL(DimDatumFilter),
			        DimDatumFilter[Jaar] = 2025 && DimDatumFilter[MaandNummer] = 2
			    )
			)
			
			```
		lineageTag: 89c9e402-46ad-40cf-90ac-47cb80a6798e

	measure Test_MaandNrRelatief = ```
			
			MAXX(
			    FILTER(
			        ALL(DimDatumFilter),
			        DimDatumFilter[Jaar] = 2025 && DimDatumFilter[MaandNummer] = 2
			    ),
			    DimDatumFilter[MaandNrRelatief]
			)
			
			```
		formatString: 0
		lineageTag: dc8db873-75ce-4c3c-9d85-c5f837ffdf9a

	measure Test_Selected_Year = ```
			SELECTEDVALUE(DimDatumFilter[Jaar])
			
			```
		lineageTag: 098591ab-aca0-405a-8b00-4ca59357a3af

	measure Test_UniekeMaandNrRelatief = ```
			
			CONCATENATEX(
			    FILTER(
			        ALL(DimDatumFilter),
			        DimDatumFilter[Jaar] = SELECTEDVALUE(DimDatumFilter[Jaar]) -- Zorgt ervoor dat er maar één jaar wordt gebruikt
			    ),
			    DimDatumFilter[MaandNrRelatief],
			    ", "
			)
			
			```
		lineageTag: 721769c1-ab00-4713-bcb3-10111c9c285d

	measure Test_UniekeMaandNrRelatief2 = ```
			
			CONCATENATEX(
			    FILTER(
			        ALL(DimDatumFilter),
			        DimDatumFilter[Jaar] = 2025 -- Forceert filter op 2025 om te testen
			    ),
			    DimDatumFilter[MaandNrRelatief],
			    ", "
			)
			
			```
		lineageTag: a1326b48-b093-4a6d-98a5-8980ec043857

	measure 'Totaalgeschreven Taakuren' =
			CALCULATE(
			    SUM(DimTaakregels[TotaalGeschrevenUren]), -- Som van TotaalGeschrevenUren
			    USERELATIONSHIP(DimTaakregels[ProjectKey], DimProjecten[ProjectKey]) -- Gebruik de alternatieve relatie
			)
		lineageTag: 2d8996b9-5467-4779-9d33-e8f39ccdf73c

	measure 'Aantal Geplande Verlofuren' =
			
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren]),
			    FeitGeschrevenUren[Verloftype] = "Regulier verlof",
			    FeitGeschrevenUren[Datum] >= TODAY()
			)
		displayFolder: Uren
		lineageTag: eda17764-a2f7-4dfc-9870-a42468e1f615

	measure 'Aantal Geschreven Projecturen Laatste 12 Maanden' = ```
			
			VAR StartDatum = EOMONTH(TODAY(), -11) + 1  -- Eerste dag van de maand 12 maanden geleden
			VAR EindDatum = TODAY()  -- Vandaag
			VAR StartJaarMaand = YEAR(StartDatum) * 100 + MONTH(StartDatum)
			VAR EindJaarMaand = YEAR(EindDatum) * 100 + MONTH(EindDatum)
			
			RETURN
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren]),
			    FeitGeschrevenUren[Projectkey] <> BLANK(),  -- Alleen projecturen
			    FeitGeschrevenUren[IsFacturabel] = TRUE(),  -- Alleen facturabele uren
			    FILTER(
			        ALL(DimDatum),
			        DimDatum[JaarMaand] >= StartJaarMaand &&
			        DimDatum[JaarMaand] <= EindJaarMaand
			    )
			)
			
			```
		displayFolder: Uren
		lineageTag: 4b94650c-ecdb-4028-9052-42c496a075aa

	measure 'Aantal Geschreven Projecturen Vorig Jaar' = ```
			
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren]),
			    NOT(ISBLANK(FeitGeschrevenUren[Projectkey])),
			    FeitGeschrevenUren[IsFacturabel] = TRUE(),
			    ISBLANK(FeitGeschrevenUren[Verloftype]),  
			    SAMEPERIODLASTYEAR(DimDatum[Datum])
			)
			
			```
		displayFolder: Uren
		lineageTag: 43dcd754-59c5-4e4f-b08f-f98a293de566

	measure 'Aantal geschreven Uren' = ```
			
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren])
			)
			
			```
		displayFolder: Uren
		lineageTag: 4c080422-2c22-47e1-a71c-74fa9cc72f12

	measure 'Aantal Geschreven Ziekteuren' = ```
			
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren]),
			    NOT(ISBLANK(FeitGeschrevenUren[Projectkey])),
			    DimTaakregels[TaakNaam] = "Ziekte / Kort Verzuim"
			)
			
			```
		displayFolder: Uren
		lineageTag: 44ef108c-f481-49c1-be80-a1d324698667

	measure 'Aantal Opgenomen Verlofuren' = ```
			
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren]),
			    FeitGeschrevenUren[Verloftype] = "Regulier verlof",
			    FeitGeschrevenUren[Datum] <= TODAY()
			)
			
			```
		displayFolder: Uren
		lineageTag: 501b6359-146e-436b-9908-41696f273dd6

	measure 'Aantal Verlofuren' = ```
			SUM(FeitVerlofAanvragen[Verlofuren])
			
			```
		displayFolder: Uren
		lineageTag: 7d5c62a7-a384-4101-9e59-33ceac367171

	measure 'Bezettingsgraad Norm' = 0.8
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Uren
		lineageTag: 55870f98-2608-4f09-aec2-9fd79548bf09

	measure 'Externe Uren' = ```
			
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren]),
			    DimProjecten[InternExtern] = "Extern"
			)
			
			```
		displayFolder: Uren
		lineageTag: cb151f1b-6f62-4737-9e66-cb91301c994c

	measure 'Facturabele Uren' = SUM(FeitGeschrevenUren[FacturabeleUren])
		displayFolder: Uren
		lineageTag: 7ad15ec2-3907-4ecf-8c31-e17011c211e5

	measure GeplandeProjectUren = ```
			
			CALCULATE(
			    SUM(FeitGeplandeUren[UrenTotaal]),
			    NOT(ISBLANK(FeitGeschrevenUren[Projectkey])),
			    FeitGeschrevenUren[IsFacturabel] = TRUE()
			)
			
			```
		displayFolder: Uren
		lineageTag: d5cb9532-a5d4-4dee-b3ad-7d29a0b65591

	measure GeplandeUren = SUM(FeitGeplandeUren[UrenTotaal])
		displayFolder: Uren
		lineageTag: 14b48316-8f97-41fc-8dda-b1500332e1e3

	measure 'Geschatte Uren' = SUM(DimProjecten[GeschatteUren])
		displayFolder: Uren
		lineageTag: ade2c330-e9f5-4d19-829e-a674d5898e0e

	measure 'Geschreven ProjectUren Laatste 12 maanden' =
			
			CALCULATE(
			    SUM(FeitGeschrevenUren[AantalUren]),
			    NOT(ISBLANK(FeitGeschrevenUren[Projectkey])),
			    FeitGeschrevenUren[IsFacturabel] = TRUE(),
			    FILTER(
			        ALL(TimeIntelligence),
			        TimeIntelligence[Calculatie] = "Laatste 12 maanden"
			    )
			)
		displayFolder: Uren
		lineageTag: 64df917f-0d98-401d-bf1c-2a6bba9356a5

	measure 'Geschreven Uren Laatste 12 maanden' =
			
			CALCULATE([Aantal geschreven Uren],
			FILTER(ALL(TimeIntelligence),
			TimeIntelligence[Calculatie] = "Laatste 12 maanden"))
		displayFolder: Uren
		lineageTag: 19722cc0-08e0-4a07-8a52-1faa150947df

	measure 'Geschreven Uren Voorgaande 12 maanden' =
			
			CALCULATE([Aantal geschreven Uren],
			FILTER(ALL(TimeIntelligence),
			TimeIntelligence[Calculatie] = "Voorgaande 12 maanden"))
		displayFolder: Uren
		lineageTag: 60a06417-a55c-4241-b9f7-30b89969995d

	measure GeschrevenProjectUren = SUM(DimProjecten[AantalUren])
		displayFolder: Uren
		lineageTag: f213952e-0b92-47df-8241-a00999c483bb

	measure 'Interne uren' =
			
			CALCULATE([Aantal geschreven Uren],
			DimProjecten[InternExtern] = "Intern"
			)
		displayFolder: Uren
		lineageTag: f3869f1a-b42f-4be3-86ac-572b5bfaa907

	measure 'Niet Facturabele Uren' = SUM(FeitGeschrevenUren[NietFacturabeleUren])
		displayFolder: Uren
		lineageTag: cef03b73-b89d-4435-b47a-9d901fb307bf

	measure Overschrijdingspercentage = ```
			
			DIVIDE(
			    [Geschrevenprojecturen] - [Geschatte uren],
			    [Geschatte uren],
			    0
			) 
			
			```
		displayFolder: Uren
		lineageTag: 73bc70e9-7c2c-4c6b-955b-0a1d185de1d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reguliere Verlofuren' =
			CALCULATE(
			    [Aantal Verlofuren],
			    FeitVerlofAanvragen[VerlofType] = "Regulier Verlof"
			)
		displayFolder: Uren
		lineageTag: 496be961-1ff3-4225-afc4-40260f1ac2d5

	measure 'Toekomstige Verlofuren Komende 12 Maanden' = ```
			
			CALCULATE(
			    SUMX(
			        SUMMARIZE(
			            FeitVerlofAanvragen,
			            FeitVerlofAanvragen[DatumAangevraagd],  -- Maak een unieke lijst van aanvraagdatums
			            "UniekeVerlofuren", MAX(FeitVerlofAanvragen[Verlofuren])  -- Pak per aanvraagdatum de max verlofuren
			        ),
			        [UniekeVerlofuren]  -- Sommeer de unieke verlofuren
			    ),
			    USERELATIONSHIP('DimDatum'[Datum], FeitVerlofAanvragen[DatumVerlof]),  -- Filter op DatumVerlof
			    FILTER(
			        ALL('DimDatum'[Datum]), 
			        'DimDatum'[Datum] > TODAY() &&
			        'DimDatum'[Datum] <= EOMONTH(TODAY(), 12)  -- Filter alleen de komende 12 maanden
			    )
			)
			```
		displayFolder: Uren
		lineageTag: c41e0c72-2981-4273-a408-4423cebe1524

	measure 'Toekomstige Verlofuren Komende 12 Maanden2' = ```
			
			CALCULATE(
			    SUMX(
			        SUMMARIZE(
			            FeitVerlofAanvragen,
			            FeitVerlofAanvragen[DatumAangevraagd],  -- Maak een unieke lijst van aanvraagdatums
			            "UniekeVerlofuren", MAX(FeitVerlofAanvragen[Verlofuren])  -- Pak per aanvraagdatum de max verlofuren
			        ),
			        [UniekeVerlofuren]  -- Sommeer de unieke verlofuren
			    ),
			    USERELATIONSHIP('DimDatum'[Datum], FeitVerlofAanvragen[DatumVerlof]),  -- Filter op DatumVerlof
			    FILTER(
			        ALL('DimDatum'[Datum]), 
			        'DimDatum'[Datum] > TODAY() &&
			        'DimDatum'[Datum] <= EOMONTH(TODAY(), 12)  -- Filter alleen de komende 12 maanden
			    )
			)
			
			```
		displayFolder: Uren
		lineageTag: aa895a08-f41f-47cf-b449-d01c4780d6b2

	measure Ziekteverzuim = [Aantal Geschreven Ziekteuren] / [Aantal geschreven Uren]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Uren
		lineageTag: d2d91183-217d-4935-a788-6415ea9bed6f

	measure Measure
		lineageTag: 1314b287-1f7e-4df8-94db-c822a3c55ac6

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Verlofsaldo = SUM(FeitVerlofSaldo[TotaalEindSaldo])
		lineageTag: b67579df-1177-46f6-aa5f-addc2509ff50

	measure VerwachteBezettingsgraad = ```
			
			DIVIDE([GeplandeUren], [BezettingsgraadBeschikbareUren], 0)
			
			```
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: e7decd33-b6fc-4606-8297-49357a48b34b

	measure VerwachteBezettingsgraadKomende12Mnd = ```
			
			CALCULATE(
			   [VerwachteBezettingsgraad],
			    FILTER(
			        ALL(TimeIntelligence),
			        TimeIntelligence[Calculatie] = "Komende 12 maanden"
			    )
			)
			
			```
		lineageTag: c198f0f6-f4d9-4094-bbc9-d856dd3d22d7

	measure VerwachteBezettingsgraadweek = ```
			
			DIVIDE([GeplandeUren], [AantalBeschikbareUrenGeselecteerdePeriode], 0)
			
			```
		lineageTag: 7ca02c12-0e6f-4d0a-9bc5-6625ec0bc823

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average FTE' = ```
			AVERAGE(FeitFormatieBezetting[FTE])
			
			```
		lineageTag: aa90443f-d431-48a9-8e52-f8cc249b172d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aantal Uren' = Sum(DimMedewerkers[AantalUren])
		formatString: 0
		lineageTag: 991b8672-a885-4fbd-b785-3c6378d5955a

	measure YTDDaysRatio =
			VAR _SelectedYear = [vHJ]
			VAR _TotalDays = CALCULATE(COUNTROWS('DimDatum'), FILTER(ALL('DimDatum') , DimDatum[Jaar] = _SelectedYear))
			VAR MAXdate = [vMaxDate]
			VAR _YTDdays = CALCULATE(COUNTROWS('DimDatum'), FILTER(ALL('DimDatum') , [Jaar] = _SelectedYear && DimDatum[Datum] <=MAXdate))
			RETURN DIVIDE( _YTDdays, _TotalDays)
		displayFolder: BudgetVsOmzet
		lineageTag: 05578b48-4d8d-4466-800b-5144675579b4

	measure vMaxDate = ```
			IF(ISFILTERED(DimDatumFilter) 
			, MIN( MAX(DimDatumFilter[Datum]) , TODAY()-1 )
			, TODAY()-1
			)
			```
		displayFolder: Variables
		lineageTag: 515a67aa-cc9f-4068-bd53-d8b9293974b3

	measure vVJ = ```
			IF(ISFILTERED(DimDatumFilter[Jaar]) 
			, MAX(DimDatumFilter[Jaar])
			, YEAR(TODAY())
			)
			```
		formatString: 0
		displayFolder: Variables
		lineageTag: 1b6cebdf-7558-4257-93d7-a5c5191343de

	measure 'YTD Budget' = [YTDDaysRatio] * [Totaal Budget]
		displayFolder: BudgetVsOmzet
		lineageTag: 78198bff-35c0-4291-8259-a5dcea60ee03

	measure 'Totaal Budget' = SUM(FeitBudgetten[Intern])
		formatString: #,0
		displayFolder: BudgetVsOmzet
		lineageTag: 0810041a-1404-4ea1-9188-21bfeb22e5d4

	measure 'Totaal Budget copy' = SUM(FeitBudgetten[Intern])
		displayFolder: BudgetVsOmzet
		lineageTag: 958ad70a-aa72-4fbc-84bc-e0409a2db055

	measure vTitelRatio =
			VAR _SelectedYear = [vHJ]
			VAR _TotalDays = CALCULATE(COUNTROWS('DimDatum'), FILTER(ALL('DimDatum') , DimDatum[Jaar] = _SelectedYear))
			VAR MAXdate = [vMaxDate]
			VAR _YTDdays = CALCULATE(COUNTROWS('DimDatum'), FILTER(ALL('DimDatum') , [Jaar] = _SelectedYear && DimDatum[Datum] <=MAXdate))
			
			RETURN "YTD Ratio" & " = " & _YTDdays & " dagen" & " / " & _TotalDays & " dagen"
		displayFolder: BudgetVsOmzet
		lineageTag: b5ef9f0d-ea94-4501-a227-ae33dff68a50

	measure 'YTD percentage' = DIVIDE([YTD Omzet ex. BTW],[YTD Budget])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: BudgetVsOmzet
		lineageTag: 4b1454d2-26db-448a-b9ab-12a6cee6be6e

	measure 'YTD Omzet ex. BTW' = ```
			VAR YR = [vHJ]
			VAR DT = [vMaxDate]
			RETURN
			CALCULATE( [Omzet ex. BTW] 
			, FILTER( ALL(DimDatum) , DimDatum[Jaar] = YR && DimDatum[Datum] <= DT))
			```
		displayFolder: Commercieel
		lineageTag: c0309100-4438-41aa-b922-6e94d0707d00

	measure 'Percentage Jaarbudget' = ```
			Divide([YTD Omzet ex. BTW], [Totaal Budget])
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: BudgetVsOmzet
		lineageTag: 8d862d06-b1f1-4325-b9a6-e38867d499e0

	measure OmzetVSBudget = [YTD Omzet ex. BTW]-[YTD Budget]
		displayFolder: BudgetVsOmzet
		lineageTag: d671f3f1-c43a-4206-bad8-9e17e2a270f2

	measure 'AVG FTE' =
			
			VAR avg1 = AVERAGE(DimMedewerkers[AantalUren])
			
			RETURN DIVIDE(avg1,40)
		lineageTag: fe5c1127-b42e-4c7b-ba69-c124997d2c57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Verhouding Omzet t.o.v. Commerciële uren' =
			VAR uurtarif = SUM(DimMedewerkers[Uurtarief])
			VAR AantalUren = SUM(DimMedewerkers[AantalUren])
			VAR tarief = uurtarif * AantalUren
			
			RETURN DIVIDE('1. Meetwaarden'[Omzet ex. BTW],tarief)
		displayFolder: Commercieel
		lineageTag: 5fd1e7ea-5287-4a29-9e82-27c76a27475c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tarief =
			VAR uurtarif = SUM(DimMedewerkers[Uurtarief])
			VAR AantalUren = SUM(DimMedewerkers[AantalUren])
			
			Return uurtarif * AantalUren
		lineageTag: 4de94643-87b3-4e32-a659-43407f83f48f

	measure 'Omzet o.b.v DatumAfgerond' =
			CALCULATE(
			    [Omzet ex. BTW],
			    USERELATIONSHIP(DimDatum[Datum], DimProjecten[DatumAfgerond])
			    )
		displayFolder: Commercieel
		lineageTag: 5bb03c13-45c3-4cbb-ba90-cd0e8f395c16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OpTijdProjecten = ```
			
			
			CALCULATE(
			COUNT(DimProjecten[ProjectId]),
			DimProjecten[OpTijdAfgerond] = 1)
			 
			```
		formatString: 0
		lineageTag: 4612eb0a-0589-4c11-82ff-d6191484a3eb

	column Column
		formatString: 0
		lineageTag: da2bfe90-c1ef-4ce2-a634-1efa6de6e22f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition '1. Meetwaarden' = calculated
		mode: import
		source = ```
				ROW("Column", BLANK())
				
				```

	annotation PBI_Id = 81f5c495ebad49dd99e298ef519701a9

