table FixedFee
	lineageTag: 8b1a533d-3c39-48b6-bf7a-b22f053a4a9f

	column Id
		dataType: string
		lineageTag: c6d4df84-c999-44f7-8ca6-e14069e60bf5
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column IsDeleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d8cb9bdf-4980-461f-a54b-66b33b15591f
		summarizeBy: none
		sourceColumn: IsDeleted

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: f03e14fe-08e6-4d11-bbae-45ab3e50d530
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column CreatedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: dc495a3a-fce3-4ef3-ac6c-199cb9c8d2f6
		summarizeBy: none
		sourceColumn: CreatedDate

		variation Variatie
			isDefault
			relationship: 46490b32-6cd7-4259-850d-089be556064f
			defaultHierarchy: LocalDateTable_25e9eaee-8af4-4555-9c11-530ec4749c0e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CreatedById
		dataType: string
		lineageTag: 6d97c564-48bf-47ab-b6f7-d8e5579cd614
		summarizeBy: none
		sourceColumn: CreatedById

		annotation SummarizationSetBy = Automatic

	column LastModifiedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: c25c0930-e1d0-4b9f-a1de-86e981dbadb3
		summarizeBy: none
		sourceColumn: LastModifiedDate

		variation Variatie
			isDefault
			relationship: 5f9f7392-55c8-469f-b869-cee4b90a6855
			defaultHierarchy: LocalDateTable_3a9007f5-c9a6-4b35-b19d-aad113ba62f8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastModifiedById
		dataType: string
		lineageTag: eb4fa207-eaec-4e7f-97b5-f455f5c38603
		summarizeBy: none
		sourceColumn: LastModifiedById

		annotation SummarizationSetBy = Automatic

	column SystemModstamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 312797f6-9137-4d99-b8fb-3d5c488c74b4
		summarizeBy: none
		sourceColumn: SystemModstamp

		variation Variatie
			isDefault
			relationship: 6d4d1da6-b322-4eb1-a3c8-15035b5835b2
			defaultHierarchy: LocalDateTable_59d1edaa-1861-40a9-93e5-e732a885b60f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastActivityDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b4f57f5-3510-424f-a334-51b23f3fa21c
		summarizeBy: none
		sourceColumn: LastActivityDate

		variation Variatie
			isDefault
			relationship: a6774062-32d4-4cfe-b03d-ad97405cbe90
			defaultHierarchy: LocalDateTable_dfc4bde4-cc08-4b0a-91a5-ee0fb6ecca93.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ConnectionReceivedId
		dataType: string
		lineageTag: ccb91f4d-74e2-47d5-bde0-26efad8e467e
		summarizeBy: none
		sourceColumn: ConnectionReceivedId

		annotation SummarizationSetBy = Automatic

	column ConnectionSentId
		dataType: string
		lineageTag: 1c4bab9e-8149-4b0f-ad49-a114e3741679
		summarizeBy: none
		sourceColumn: ConnectionSentId

		annotation SummarizationSetBy = Automatic

	column Krow__Project_Billing__c
		dataType: string
		lineageTag: 7c1a1fb8-10ce-4fa7-a446-7693817585bd
		summarizeBy: none
		sourceColumn: Krow__Project_Billing__c

		annotation SummarizationSetBy = Automatic

	column Krow__Amount__c
		dataType: double
		lineageTag: 3ad5f43c-51fd-4045-9d33-a0e391390c08
		summarizeBy: sum
		sourceColumn: Krow__Amount__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Billing_Method__c
		dataType: string
		lineageTag: cec75f4a-4b17-4423-ad4b-a619d3e9d088
		summarizeBy: none
		sourceColumn: Krow__Billing_Method__c

		annotation SummarizationSetBy = Automatic

	column Krow__Date__c
		dataType: dateTime
		formatString: Long Date
		lineageTag: 64a79213-cb48-4a9f-a87e-719bdd7f56a6
		summarizeBy: none
		sourceColumn: Krow__Date__c

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Krow__Description__c
		dataType: string
		lineageTag: 08e2d59e-92c2-4243-9f97-7b6d6008c3f3
		summarizeBy: none
		sourceColumn: Krow__Description__c

		annotation SummarizationSetBy = Automatic

	column Krow__Discount__c
		dataType: double
		lineageTag: 394bfbd2-de6d-4886-8525-736ecd7db589
		summarizeBy: sum
		sourceColumn: Krow__Discount__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__End_Date__c
		dataType: dateTime
		formatString: General Date
		lineageTag: b46caf5e-d806-421e-96b6-9d4fb1cc806d
		summarizeBy: none
		sourceColumn: Krow__End_Date__c

		variation Variatie
			isDefault
			relationship: 661441d0-1862-4437-881a-31097e5d7207
			defaultHierarchy: LocalDateTable_ded98fa2-72ac-42a3-8af6-8ffd30e2fcf6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Krow__Hours__c
		dataType: double
		lineageTag: bd24028a-358a-4c50-b7bc-0a61f664b917
		summarizeBy: sum
		sourceColumn: Krow__Hours__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Invoiced__c
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a0427e7-f817-4cea-88bc-d64196d33bc3
		summarizeBy: none
		sourceColumn: Krow__Invoiced__c

		annotation SummarizationSetBy = Automatic

	column Krow__Markup__c
		dataType: double
		lineageTag: e2e35741-9255-40f7-be6f-b803a8e54099
		summarizeBy: sum
		sourceColumn: Krow__Markup__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Overage_Amount__c
		dataType: double
		lineageTag: 0507949e-cc18-4b77-8fae-0482bb2f7e21
		summarizeBy: sum
		sourceColumn: Krow__Overage_Amount__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Percentage__c
		dataType: double
		lineageTag: 708c9e11-db6f-40e3-968a-069a672a1e0c
		summarizeBy: sum
		sourceColumn: Krow__Percentage__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Quantity__c
		dataType: double
		lineageTag: f4110bf2-db98-4f77-918c-9aacfd8705ee
		summarizeBy: sum
		sourceColumn: Krow__Quantity__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Sale_Price__c
		dataType: double
		lineageTag: e763b9c0-2e64-472f-988a-6c741ec4ee21
		summarizeBy: sum
		sourceColumn: Krow__Sale_Price__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Total_Billable_Hours__c
		dataType: double
		lineageTag: 778f2a59-ff42-4335-b179-3e7869d5dfd0
		summarizeBy: sum
		sourceColumn: Krow__Total_Billable_Hours__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Total_Timesheet_Amount__c
		dataType: double
		lineageTag: f5a6107d-1f07-4524-ae96-39b615ed8eb6
		summarizeBy: sum
		sourceColumn: Krow__Total_Timesheet_Amount__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Total_Timesheet_Hour__c
		dataType: double
		lineageTag: dd7f9807-f252-4199-adde-5c4428071c6b
		summarizeBy: sum
		sourceColumn: Krow__Total_Timesheet_Hour__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Krow__Klient_Project__c
		dataType: string
		lineageTag: e98267c8-9411-4cb6-aa0d-a7fa6f78e8dd
		summarizeBy: none
		sourceColumn: Krow__Klient_Project__c

		annotation SummarizationSetBy = Automatic

	column Create_new_Project_Billing_Line__c
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d4ac420c-9b48-4c7e-a8f4-b078ca9670e0
		summarizeBy: none
		sourceColumn: Create_new_Project_Billing_Line__c

		annotation SummarizationSetBy = Automatic

	partition FixedFee = m
		mode: import
		queryGroup: Dim
		source =
				let
				    Source = Sql.Database("6axb2xb7kkaujnz5lqc35xokhe-jtbihupxli3unlh5ujz4xsn2je.datawarehouse.fabric.microsoft.com", "Operationeel Dashboard"),
				    s4_inf_FixedFees = Source{[Schema="s4_inf",Item="FixedFees"]}[Data],
				    #"Type gewijzigd" = Table.TransformColumnTypes(s4_inf_FixedFees,{{"Krow__Date__c", type date}})
				in
				    #"Type gewijzigd"

	annotation PBI_NavigationStepName = Navigatie

	annotation PBI_ResultType = Table

